name: Npm Test

on:
  pull_request:
    branches:
      - feature/*

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: npm test
        uses: actions/checkout@v2
        run: |
          npm i
          npm test
