name: Npm Test

env:
  TZ: 'Asia/Tokyo'

on:
  pull_request:
    branches:
      - feature/*

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: execute npm test
        run: |
          npm i
          npm test
