name: Npm Test

on:
  pull_request:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: npm test
        run: |
          npm i
          npm test
